name: {{project_name}}
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.38.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  {{#use_localization}}
  flutter_localizations:
    sdk: flutter
  {{/use_localization}}
  # sembast database & encryption
  sembast: 3.8.5+2
  sembast_web: 2.4.2
  encrypt: 5.0.3
  crypto: 3.0.7
  path_provider: 2.1.5
  rxdart: 0.28.0

  # riverpod
  flutter_riverpod: 3.0.3
  riverpod_annotation: 3.0.3

  # launcher icons
  flutter_launcher_icons: 0.14.4
  {{#use_splash}}
  # splash screen
  flutter_native_splash: 2.4.7
  {{/use_splash}}
  {{#use_firebase}}
  # firebase
  firebase_core: 4.2.1
  firebase_messaging: ^16.0.4
  {{^use_sentry}}firebase_crashlytics: ^5.0.5{{/use_sentry}}
  firebase_analytics: ^12.0.4
  {{/use_firebase}}
  # screenutil & internet connection checker
  flutter_screenutil: 5.9.3
  internet_connection_checker_plus: 2.9.1

  google_fonts: 6.3.2
  go_router: 17.0.0
  lazy_load_indexed_stack: 1.2.1
  {{#use_dio}}
  # dio
  dio: 5.9.0
  alice_dio: ^1.0.7
  alice: ^1.0.0
  {{/use_dio}}
  {{#use_sentry}}
  # sentry
  sentry_flutter: ^9.9.2
  {{/use_sentry}}
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.2.2
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.10.2
  custom_lint:
  riverpod_generator: 3.0.3
  riverpod_lint: 3.0.3
  flutter_flavorizr: 2.4.1

flutter:
  uses-material-design: true
  {{#use_localization}}
  # Enable generation of localized Strings from arb files.
  generate: true
  {{/use_localization}}
  assets:
    - assets/
    - assets/icons/


# Flutter Launcher Icons configuration
flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/common/app-icon.png"
  image_path_ios_dark_transparent: "assets/common/app-icon-transparent.png"
  image_path_android: "assets/android/app-icon-android.png"
  adaptive_icon_background: "assets/android/app-icon-background.png"
  adaptive_icon_foreground: "assets/android/app-icon-foreground.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/common/app-icon.png"
{{#use_splash}}
# Flutter Native Splash configuration
flutter_native_splash:
  color: "#ffffff"
  image: "assets/common/app-splash.png"
  android_12:
    color: "#ffffff"
    icon_background_color: "#FFFFFF"
    image: "assets/common/app-splash.png"
{{/use_splash}}
# Flavorizr configuration
flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"
    
  flavors:
    dev:
      app:
        name: "{{app_name}} [DEV]"
      android:
        applicationId: "{{app_id}}.dev"
      ios:
        bundleId: "{{app_id}}.dev"
        icon: "assets/common/app-icon.png"
    
    stg:
      app:
        name: "{{app_name}} [STG]"
      android:
        applicationId: "{{app_id}}.stg"
      ios:
        bundleId: "{{app_id}}.stg"
        icon: "assets/common/app-icon.png"
    
    prod:
      app:
        name: "{{app_name}}"
      android:
        applicationId: "{{app_id}}"
      ios:
        bundleId: "{{app_id}}"
        icon: "assets/common/app-icon.png"
